teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.8
    scale_linear_turbo:
      x: 0.6

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.8
    scale_angular_turbo:
      yaw: 2.5

    enable_button: 1  # Green "A" button
    enable_turbo_button: 10  # L1 shoulder button